In [ ]:
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv


In [ ]:
import pandas as pd
import numpy as np
import io
data = pd.read_csv(io.BytesIO(uploaded['emails.csv']))

In [ ]:
data.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [ ]:
Y = data['Prediction']
X = data.drop(['Email No.','Prediction'],axis = 1)

In [ ]:
X.head()

the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  connevey  \
0    0   0    1    0    0   0    2    0    0   0  ...             0         0   
1    8  13   24    6    6   2  102    1   27  18  ...             0         0   
2    0   0    1    0    0   0    8    0    0   4  ...             0         0   
3    0   5   22    0    5   1   51    2   10   1  ...             0         0   
4    7   6   17    1    5   2   57    0    9   3  ...             0         0   

   jay  valued  lay  infrastructure  military  allowing  ff  dry  
0    0       0    0               0         0         0   0    0  
1    0       0    0               0         0         0   1    0  
2    0       0    0               0         0         0   0    0  
3    0       0    0               0         0         0   0    0  
4    0       0    0               0         0         0   1    0  

[5 rows x 3000 columns]

In [ ]:
X = X.to_numpy()
Y = Y.to_numpy()

In [ ]:
print(X.shape)
print(Y.shape)

(5172, 3000)
(5172,)


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

print(X_train.shape)
print(X_test.shape)

(4137, 3000)
(1035, 3000)


In [ ]:
#Logisitc regression
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0, max_iter = 1000)
clf.fit(X_train,y_train)

LogisticRegression(max_iter=1000, random_state=0)

In [ ]:
def Scores(X_train,y_train,X_test,y_test, clf):
    
    y_pred = clf.predict(X_test)
    tn, fp, fn, tp = confusion_matrix(y_test,y_pred).ravel()
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)

    print("Train Set Accuracy = {}".format(clf.score(X_train, y_train)))
    print("Test Set Accuracy = {}".format(clf.score(X_test,y_test)))
    print("F1 Score = {}".format(f1_score(y_test,y_pred)))
    print("Confusion Matrix")
    print(confusion_matrix(y_test,y_pred))
    print("Precision = {} Recall = {}".format(precision,recall))
    
    return None

In [ ]:
#Acuracy Check on Logistic Regression
Scores(X_train,y_train,X_test,y_test, clf)

Train Set Accuracy = 0.9995165578921924
Test Set Accuracy = 0.9719806763285024
F1 Score = 0.9514237855946398
Confusion Matrix
[[722  17]
 [ 12 284]]
Precision = 0.9435215946843853 Recall = 0.9594594594594594


In [ ]:
#GDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

clf = LinearDiscriminantAnalysis()
clf.fit(X_train,y_train)

LinearDiscriminantAnalysis()

In [ ]:
#Accuracy Check on Linear Discriminant Analysis
Scores(X_train,y_train,X_test,y_test, clf)

Train Set Accuracy = 0.9954072999758279
Test Set Accuracy = 0.7613526570048309
F1 Score = 0.5957446808510638
Confusion Matrix
[[606 133]
 [114 182]]
Precision = 0.5777777777777777 Recall = 0.6148648648648649


In [ ]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

clf = QuadraticDiscriminantAnalysis()
clf.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


QuadraticDiscriminantAnalysis()

In [ ]:
#Accuracy Check on Quadratic Discriminant Analysis
Scores(X_train,y_train,X_test,y_test, clf)

Train Set Accuracy = 0.9963741841914431
Test Set Accuracy = 0.7497584541062802
F1 Score = 0.2492753623188406
Confusion Matrix
[[733   6]
 [253  43]]
Precision = 0.8775510204081632 Recall = 0.14527027027027026


In [ ]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf.fit(X_train,y_train)

MultinomialNB()

In [ ]:
#Accuracy Check on MultinomialNB
Scores(X_train,y_train,X_test,y_test, clf)

Train Set Accuracy = 0.9661590524534687
Test Set Accuracy = 0.9478260869565217
F1 Score = 0.9131832797427653
Confusion Matrix
[[697  42]
 [ 12 284]]
Precision = 0.8711656441717791 Recall = 0.9594594594594594


In [ ]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
clf.fit(X_train,y_train)

GaussianNB()

In [ ]:
GaussianNB()

#Accuracy Check on GaussianNB
Scores(X_train,y_train,X_test,y_test, clf)

Train Set Accuracy = 0.9661590524534687
Test Set Accuracy = 0.9478260869565217
F1 Score = 0.9131832797427653
Confusion Matrix
[[697  42]
 [ 12 284]]
Precision = 0.8711656441717791 Recall = 0.9594594594594594


In [ ]:
from sklearn.naive_bayes import BernoulliNB

clf = BernoulliNB()
clf.fit(X_train,y_train)

BernoulliNB()

In [ ]:
#Accuracy Check on BernoulliNB
Scores(X_train,y_train,X_test,y_test, clf)

#Poor Accuracy Expected due to the way data we have
#Counting Number of words is used for MultinomialNB

Train Set Accuracy = 0.8716461203770849
Test Set Accuracy = 0.8966183574879227
F1 Score = 0.81326352530541
Confusion Matrix
[[695  44]
 [ 63 233]]
Precision = 0.8411552346570397 Recall = 0.7871621621621622


In [ ]:
from sklearn.svm import SVC

clf = SVC(kernel = 'linear')
clf.fit(X_train,y_train)

SVC(kernel='linear')

In [ ]:
#Accuracy Check on Support Vector Classification
Scores(X_train,y_train,X_test,y_test, clf)

Train Set Accuracy = 0.9997582789460963
Test Set Accuracy = 0.9594202898550724
F1 Score = 0.9297658862876255
Confusion Matrix
[[715  24]
 [ 18 278]]
Precision = 0.9205298013245033 Recall = 0.9391891891891891


In [ ]:
#Neural network
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, BatchNormalization
from tensorflow.keras import Input
model = keras.Sequential(
[
    Input((3000)),
    Dense(64, activation = 'relu'),
    Dense(32, activation = 'relu'),
    Dense(32, activation = 'relu'),
    Dense(1, activation = 'sigmoid')
])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                192064    
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 32)                1056      
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 195,233
Trainable params: 195,233
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss = 'binary_crossentropy', optimizer = 'Adam',metrics=['accuracy',keras.metrics.Precision(), keras.metrics.Recall()])

In [ ]:
y_train = np.reshape(y_train,(y_train.shape[0]))
print(X_train.shape)
print(y_train.shape)

(4137, 3000)
(4137,)


In [ ]:
history = model.fit(X_train,y_train, epochs = 10, validation_data=(X_test,y_test), batch_size = 16)

Epoch 1/10
259/259 [==============================] - 3s 6ms/step - loss: 0.3643 - accuracy: 0.8663 - precision: 0.8163 - recall: 0.6977 - val_loss: 0.1345 - val_accuracy: 0.9623 - val_precision: 0.9509 - val_recall: 0.9155
Epoch 2/10
259/259 [==============================] - 1s 4ms/step - loss: 0.1764 - accuracy: 0.9550 - precision: 0.9277 - recall: 0.9169 - val_loss: 0.1080 - val_accuracy: 0.9739 - val_precision: 0.9719 - val_recall: 0.9358
Epoch 3/10
259/259 [==============================] - 1s 4ms/step - loss: 0.0907 - accuracy: 0.9773 - precision: 0.9542 - recall: 0.9684 - val_loss: 0.0795 - val_accuracy: 0.9768 - val_precision: 0.9564 - val_recall: 0.9628
Epoch 4/10
259/259 [==============================] - 1s 4ms/step - loss: 0.0479 - accuracy: 0.9850 - precision: 0.9711 - recall: 0.9776 - val_loss: 0.1760 - val_accuracy: 0.9585 - val_precision: 0.8799 - val_recall: 0.9899
Epoch 5/10
259/259 [==============================] - 1s 4ms/step - loss: 0.0448 - accuracy: 0.9865 - pr

In [ ]:
print("Train Accuracy = {}".format(history.history['accuracy'][9]) )
print("Test Accuracy = {}".format(history.history['val_accuracy'][9]) )
print("Precision = {}".format(history.history['val_precision'][9]) )
print("Recall = {}".format(history.history['val_recall'][9]) )
print("Confusion Matrix")
y_pred = model.predict(X_test)
print(confusion_matrix(y_test,y_pred.round()))
print("F1 Score = {}".format(f1_score(y_test,y_pred.round())))

Train Accuracy = 0.9997583031654358
Test Accuracy = 0.9777777791023254
Precision = 0.95652174949646
Recall = 0.9662162065505981
Confusion Matrix
[[726  13]
 [ 10 286]]
F1 Score = 0.9613445378151261
